# 
# Synthesis run script generated by Vivado
# 

set_param project.defaultXPMLibraries XPM_MEMORY
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /disk0/Work/xike_hls_module/rt_feedback/rt_feedback/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path /disk0/Work/xike_hls_module/rt_feedback/rt_feedback/solution1/impl/verilog/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /disk0/Work/xike_hls_module/rt_feedback/rt_feedback/solution1/impl/verilog/rt_feedback.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /disk0/Work/xike_hls_module/rt_feedback/rt_feedback/solution1/impl/verilog/rt_feedback.xdc
set_property used_in_implementation false [get_files /disk0/Work/xike_hls_module/rt_feedback/rt_feedback/solution1/impl/verilog/rt_feedback.xdc]


synth_design -top rt_feedback -part xc7k325tffg900-2 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef rt_feedback.dcp

catch { report_utilization -file rt_feedback_utilization_synth.rpt -pb rt_feedback_utilization_synth.pb }
